test gha dependency graph

diff --git a/.github/workflows/cd-github.yaml b/.github/workflows/cd-github.yaml
--- a/.github/workflows/cd-github.yaml
+++ b/.github/workflows/cd-github.yaml
@@ -41,8 +41,38 @@ permissions:
   #variables: write
 
 jobs:
+  is-latest-checkout:
+    name: "Check if current commit is latest"
+    # We want to avoid running terraform plan/apply on stale commits
+    #   this avoid accidently re-running an old GHA.
+    runs-on: ubuntu-latest
+
+    steps:
+      - name: Checkout
+        id: checkout
+        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
+
+      - name: Check branch-head equals current checkout
+        id: run-version-check
+        env:
+          BRANCH_NAME: ${{ github.ref }}
+          GITHUB_SHA: ${{ github.sha }}
+        shell: bash
+        run: |
+          set -euo pipefail
+
+          ORIGIN_SHA=$(git ls-remote origin "${BRANCH_NAME}" | awk '{print $1}')
+          echo "current sha: ${GITHUB_SHA}"
+          echo "origin sha: ${ORIGIN_SHA}"
+
+          if [[ "${GITHUB_SHA}" != "${ORIGIN_SHA}" ]]; then
+            echo "current sha(${GITHUB_SHA}) is NOT the latest origin sha(${ORIGIN_SHA}) -- pipeline aborted."
+            exit 10
+          fi
+
   deploy-curator:
     uses: ./.github/workflows/deploy-terraform.yaml
+    needs: is-latest-checkout
     with:
       environment_name: RKurator
       apply_terraform: false
@@ -51,6 +81,7 @@ jobs:
     name: Terraform
     runs-on: ubuntu-latest
     environment: RKurator
+    needs: is-latest-checkout
     steps:
       - name: Generate Token
         # Used to provide feedback
